name: "Hello Actions"
description: "Greet JOnay"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Jonay"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"